---
- name: Include common prepare
  import_playbook: provisioning/AZURE/prepare.yml

- name: Install java
  hosts: windows
  roles:
    - role: lean_delivery.java
  tasks:
    - name: Install NuGet
      win_shell: 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'
      changed_when: false
