---
- name: Check zk_root_url
  block:
    - name: Check zk_root_url
      uri:
        url: '{{ zk_root_url }}/{{ zk_version }}'
        return_content: true
      register: zk_root_page
  rescue:
    - name: Check zk_root_url
      uri:
        url: '{{ zk_root_url }}/zookeeper-{{ zk_version }}'
        return_content: true
      register: zk_root_page

- name: Set zk_version
  set_fact:
    zk_version: >-
      {{ zk_root_page.content
          | regex_findall('[\D-]*([\d\.]+)(-bin)?\.tar.gz')
          | first | list | first }}

- name: Zookeeper Installation
  include_tasks: '{{ zk_install_type }}.yml'

- name: Start and Enable zookeeper service
  service:
    name: '{{ zk_service_name }}'
    enabled: '{{ zk_service_autostart | bool }}'
    state: started
  become: true
  when:
    - zk_service_start | bool
