---

- name: Install 7zip
  win_chocolatey:
    name: 7zip
    state: present

- name: Install PSCX
  win_psmodule:
    name: Pscx
    state: present
    allow_clobber: true

- name: Get artifact checksum file
  win_uri:
    url: '{{ zk_url }}.{{ zk_checksum }}'
    return_content: true
  register: artifact_checksum_file

- name: Get artifact checksum
  set_fact:
    artifact_checksum: '{{ artifact_checksum_file.content.split(" ")[0] }}'

- name: Ansible 2.7 fetch
  include_tasks: fetch_old.yml
  when: ansible_version.full is version('2.8.0', '<')

- name: 'Download artifact from {{ zk_url }}'
  win_get_url:
    url: '{{ zk_url }}'
    dest: '{{ zk_tarball_dir }}/{{ zk_file_url }}'
    force: true
    checksum: '{{ artifact_checksum }}'
    checksum_algorithm: '{{ zk_checksum }}'
  when: ansible_version.full is version('2.8.0', '>=')

- name: Unarchive gz
  win_unzip:
    src: '{{ zk_tarball_dir }}\{{ zk_file_url }}'
    dest: '{{ zk_tarball_dir }}'
    recurse: false
    creates: '{{ zk_tarball_dir }}\{{ zk_file_url | splitext | first }}'

- name: Unzip tar
  win_command: '7z x -y {{ zk_file_url | splitext | first }}'
  args:
    chdir: '{{ zk_tarball_dir }}'
    creates: '{{ zk_tarball_dir }}\{{ zk_file_url | splitext | first | splitext | first }}'

- name: Creates home directory
  win_file:
    path: '{{ zk_dir }}'
    state: directory

- name: List zk directory
  win_find:
    paths: '{{ zk_tarball_dir }}\{{ zk_file_url | splitext | first | splitext | first }}'
    recurse: yes
  register: zk_dir_files

- name: Out zk_dir_files
  debug:
    var: zk_dir_files.files

- name: Copy unarchived tarball to home directory
  win_copy:
    src: '{{ zk_tarball_dir }}\{{ zk_file_url | splitext | first | splitext | first }}\'
    dest: '{{ zk_dir }}'
    remote_src: true
